apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter-service
  namespace: exporter
spec:
  selector:
    app: speedtest-exporter-app
  ports:
    - port: 9112
      targetPort: 9112
---

apiVersion: v1
kind: Service
metadata:
  name: bitcoin-exporter-service
  namespace: exporter
spec:
  selector:
    app: bitcoin-exporter-app
  ports:
    - port: 9100
      targetPort: 9100

---

apiVersion: v1
kind: Service
metadata:
  name: ping-check-exporter-service
  namespace: exporter
spec:
  selector:
    app: ping-check-exporter-app
  ports:
    - port: 9100
      targetPort: 9100
---

apiVersion: v1
kind: Service
metadata:
  name: dns-check-exporter-service
  namespace: exporter
spec:
  selector:
    app: dns-check-exporter-app
  ports:
    - port: 9100
      targetPort: 9100
---

apiVersion: v1
kind: Service
metadata:
  name: reconnect-exporter-service
  namespace: exporter
spec:
  selector:
    app: reconnect-exporter-app
  ports:
    - port: 9100
      targetPort: 9100
