apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: registry.tino.sh/speedtest-exporter
    context: ../../
    docker:
      target: speedtest-exporter
  - image: registry.tino.sh/bitcoin-exporter
    context: ../../
    docker:
      target: bitcoin-exporter
  - image: registry.tino.sh/ping-check-exporter
    context: ../../
    docker:
      target: ping-check-exporter
  - image: registry.tino.sh/dns-check-exporter
    context: ../../
    docker:
      target: dns-check-exporter
  - image: registry.tino.sh/reconnect-exporter
    context: ../../
    docker:
      target: reconnect-exporter
deploy:
  kustomize: {}
