apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: speedtest-exporter-app
  name: speedtest-exporter-app
  namespace: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter-app
  template:
    metadata:
      labels:
        app: speedtest-exporter-app
    spec:
      containers:
      - name: speedtest-exporter-app
        image: registry.tino.sh/speedtest-exporter
        resources:
          requests:
            memory: "40Mi"
            cpu: "60m"
          limits:
            memory: "100Mi"
            cpu: "180m"
        ports:
        - containerPort: 9112
