{
 "title": "Speedtest",
 "description": "Speedtest metrics",
 "time": { "from": "now-4d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "ISP",
    "label": "ISP",
    "query": {
     "query": "label_values(speedtest_latency_seconds, user_isp)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "yaxes": [
    { "format": "Mibits" }
   ],
   "targets": [
    { "expr": "avg(speedtest_download)", "legendFormat": "Download" },
    { "expr": "avg(speedtest_upload)", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_download[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_download[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_download[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_upload[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_upload[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_upload[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "speedtest_ping", "legendFormat": "ping" }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_ping[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "max(max_over_time(speedtest_ping[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_ping[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  }
 ]
}